[build]
  command = "next build"
  publish = ".next"

# This ensures that environment variables are available during the build process.
[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://xwobggszxxdnlzzhgkff.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3b2JnZ3N6eHhkbmx6emhna2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTUxNjIsImV4cCI6MjA3MTk3MTE2Mn0.cAI3Tp5ihJY7jPiCGCNN9GAQAHUYcvoaLCOIYTk77_o"
  # Make sure to set GEMINI_API_KEY in your Netlify site settings.

[[plugins]]
  package = "@netlify/plugin-nextjs"
